version: '3.3'

services:
  nginx:
    image: 'nginx:1.13-alpine'
    restart: 'unless-stopped'
    expose:
       - "80"
       - "443"
    ports:
       - "80:80"
       - "443:443"
    volumes:
       - ./:/usr/share/nginx/html/
   
